### Gemfile for building by GitHub Pages using remote themes

source "https://rubygems.org"

gem "github-pages", "~> 228", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-include-cache"
  gem "jekyll-feed", "~> 0.12"
end
